### ISSUE TITLE
Missing semicolon inserted in the wrong place

### ISSUE THREAD

**Issue by rousskov** [Mark-Simulacrum/attractifier#9]
When processing [ReportFigures.js](https://fossies.org/dox/polygraph-4.9.0-src/ReportFigures_8js_source.html), attractifier correctly inserts a missing semicolon after `createHelp` declaration but it picks the wrong place for it:

```
     }
 
+    ;
     TheShowHandlers['interactive'] = function (fig) {
```

**Comment by Mark-Simulacrum** [comment]
Should be fixed in version 1.6.3.

**Comment by rousskov** [comment]
Cannot confirm: The bug is still there AFAICT. No change in formatting.

**Comment by rousskov** [comment]
@Mark-Simulacrum, you may want to remove the `Waiting for confirmation of fix` label.

**Comment by Mark-Simulacrum** [comment]
Confirmed that this is still a problem.

The semicolon is inserted by `ensure(";")` after a call to `ensureVoid()`; the void ensure sees `\n\n` as significant whitespace and proceeds to insert it. That means that we'll insert the semicolon _after_ the newlines. We want to do the reverse but it's not clear how to do so -- we sort of want to "buffer" until we see the semicolon, insert the semicolon, and then the buffer. But how to do that isn't really clear.

**Comment by rousskov** [comment]
Is something important (more) likely to break if we `ensure(";")` _before_ `ensureVoid()`? If that results in extra/bare semicolons in some cases, then perhaps some other rule can remove those?
